baseURL = "https://wastemobile.github.io/goproto/"
languageCode = "zh-TW"
defaultContentLanguage = "zh-TW"
hasCJKLanguage = true

title = "hugoProto"

publishDir = "docs"

[params]
	subtitle = "Hugo Prototype with Bulma"